apiVersion: v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: webservice
  name: webservice
spec:
  backend:
    serviceName: webservice
    servicePort: 80
  rules:
    - host: server.test
      http:
        paths:
          - path: /
            backend:
              serviceName: webservice
              servicePort: 80
