apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresclaim
  labels:
    app: webservice
    tier: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
