apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: webservice
    tier: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: webservice
    tier: postgres
