apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgresql:latest
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /data/pgdata
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgres
